[language-server]
jdtls = { command = "jdtls", args = ["-data /dev/java", "--jvm-arg=-javaagent:/usr/local/lib/lombok/lombok.jar"]}

[[language]]
name = "java"
scope = "source.java"
injection-regex = "java"
file-types = ["java"]
roots = ["pom.xml", "build.gradle"]
language-servers = [ "jdtls" ]
indent = { tab-width = 4, unit = "    " }
